# -*- coding: utf-8 -*-
"""600_FinalProject_Orio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14TzqOFxnCSt2aKvIKM0oFx2i1Xr9RYLg

# Title: **Predicting Price Crisis 3 Months Ahead**

## **1. Business Understanding**

The Bureau of **Price Stability**(BPS) is a specialized unit under the Department of Agriculture. Their mission is to ensure essential commodities remain affordable for Filipinos. BPS also manage the national food supply chain and advise the government on when to intervene in the market like when to import or when to provide subsidies for farmers.

Problem: The prices of essential goods fluctuate wildly throughout the year due to weather, holidays, and supply chain cycles.

Importance: Data-drive forecasting is critical too ensure the BPS is can act immediately when a price crisis happens. For example, intervening late after prices spiked often leaving the low income families in crisis. It takes weeks to import or move the stock, leaving a hunger gap.

Goal: To forecast the monthly seasonal peaks and volatility of essential food categories 3 months in advance to identify 'High-Risk' months for price inflation.

Business-Related Questions:


1.   How was the average price of Cereals and Tubers vs Meat, Fish and Egg evolved in the Philippines from 2000 to the present?

2.   Are there spefic period or years that show unusual price spikes compared to the historical average?

3.  Which months consistenly show the highest Seasonality index for Meat vs Rice?

4.  Can we build a model that accurately flags a Price Volatility at least 90 days before it occurs?

5.  What is the error tolerance for our predictions before they become risky for policy-making?

# **2.  Data Understanding**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import gdown
import os
import streamlit as st    
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

st.set_page_config(layout="wide")
st.config.set_option("client.showErrorDetails", True)

df = pd.read_csv('wfp_food_prices_phl.csv')

for col in df.columns:
    # If a column is a pandas specialized String Extension or an generic Object type
    if str(df[col].dtype) in ['string', 'object', 'category']:
        # Force it to a native, clean standard Python string format
        df[col] = df[col].astype(str)
df = pd.DataFrame(df.to_dict(orient='list'))
df.head(10)

print(df.info())
print(df.describe(include='all'))

"""# **Data Types**"""

df.dtypes

"""How many missing values exist for each variable?"""

print("\nMissing Values: ")
print(df.isna().sum())

plt.figure(figsize=(10,5))
sns.histplot(df['price'], bins=50, kde=True)
plt.title('Distribution of Prices')
plt.show()

plt.figure(figsize=(12,6))
sns.boxplot(data=df, x='category', y='price')
plt.xticks(rotation=45)
plt.title('Price Distribution by Category')
plt.show()

df['date'] = pd.to_datetime(df['date'])

plt.figure(figsize=(15,6))
df.groupby('date')['price'].mean().plot()
plt.title('Average National Food Price Trend (2000-2026)')
plt.ylabel('Price(PHP)')
plt.show()

"""### **EDA Questions:**

1.  **What is the size of the dataset?**
The dataset consists of 225,608 rows and 16 columns

2.  **What is the time period or coverage?**
The data covers 25 years of historical market data, starting from 2001 of January 15.

3. **What are the mean, min, max, and standard deviation of the main target variable(Price or Price over time)?**
Mean: 130.16 PHP, Min: 1.60 PHP, Max: 1,216.67 PHP, Std Dev: 118.56 PHP

4. **How many values exists for each variable?**
According to the df.info, every column has 225,608 non-null values, meaning there are 0 missing values. This indicates that the World Food Programme has already curate the dataset.

5.  **Are there obvious outliers or extreme values?**
The mean is much closer to min than the max.

# **3.  DATA PREPARATION**

Duplicate Handling
"""

duplicates = df.duplicated().sum()
print(f"Duplicates found: {duplicates}")

"""Feature Engineering"""

df['date'] = pd.to_datetime(df['date'])
df.loc[:, 'year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['price_lag_3'] = df.groupby(['market_id', 'commodity_id'])['price'].shift(3)

df= df.dropna(subset=['price_lag_3'])

"""Outlier Handling      """

q_upper = df['price'].quantile(0.99)
df['price'] = df['price'].clip(upper = q_upper)

"""Encoding Categorical Variables"""

le = LabelEncoder()
df['commodity_encoded'] = le.fit_transform(df['commodity'])
df['pricetype_encoded'] = le.fit_transform(df['pricetype'])

"""Train Test Split"""

df = df.sort_values('date')
train_size = int(len(df) * 0.8)
train = df.iloc[:train_size]
test = df.iloc[train_size:]

print(f"Training set size: {len(train)}")
print(f"Test set size: {len(test)}")

"""**Duplicate Handling**
What: Identified whether there is duplicated rows
Why: Duplicates can lead to overfitting, causing the model to give too much importance to specific price points that don't reflect actual market frequency

**Feature Engineering**
What:Extracted the month and created a price_lag_3 feature, which represents the price three months prior to the current now.
Why: the model needs to learn the relationship between what is happening now and what will happen next quarter

**Outlier Handling**
What: used the 99th percentile to cap the extreme price values
Why: Extreme outliers can distort the standard deviation, making model struggle to find the true seasonal baseline.

**Encoding Categorical Values**
What: Convert the commodity and pricetype into numerical values using label encoding

**Train Test Split**
What: sorted the dataset by date and split it so the model trains on the first 80% of history and is tested on the most recent 20%
Why: it ensures the model will actually predict unseen future data

# 4.  **Modeling**

For Modeling section we will use Linear Regression for the baseline model and Random Forest Regression for advance model. The goal is to predict the price of a specific commodity 3 months from now based on the price today and the month.

Linear Regression
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error, r2_score

features = ['month', 'year', 'commodity_encoded', 'pricetype_encoded', 'price_lag_3']
target = 'price'

X_train = train[features]
y_train = train[target]
X_test = test[features]
y_test = test[target]

baseline_model = LinearRegression()
baseline_model.fit(X_train, y_train)
baseline_predictions = baseline_model.predict(X_test)

baseline_mae = mean_absolute_error(y_test, baseline_predictions)
baseline_mse = mean_squared_error(y_test, baseline_predictions)
baseline_rmse = np.sqrt(baseline_mse)
baseline_r2 = r2_score(y_test, baseline_predictions)
print(f"Linear Regression Metrics: ")
print(f"MAE: {baseline_mae}")
print(f"MSE: {baseline_mse}")
print(f"RMSE: {baseline_rmse}")
print(f"R2 Score: {baseline_r2}")

"""Random Forest Regressor"""

rf_model = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42)
rf_model.fit(X_train, y_train)
rf_predictions = rf_model.predict(X_test)

rf_mae = mean_absolute_error(y_test, rf_predictions)
rf_mse = mean_squared_error(y_test, rf_predictions)
rf_rsme = np.sqrt(rf_mse)
rf_r2 = r2_score(y_test, rf_predictions)

print(f"Random Forest Regression Metrics: ")
print(f"MAE: {rf_mae}")
print(f"MSE: {rf_mse}")
print(f"RMSE: {rf_rsme}")
print(f"R2 Score: {rf_r2}")

"""1. **Which algorithms did you use and why are they appropriate?**
I used Linear Regression as Baseline model and Random Forest Regressor as the advance model. Random forest is appropriate because market prices don't always move in straight line; it can capture complex seasonal logic and the interaction between different commodities and locations using decision trees.

2.  **What features are used to predict the target?**
the feature used are: 'months': to capture recurring annual seasonality, 'year':captures long term inflation trend, 'commodity_encoded':identifies specific product, 'pricetype_encoded': differentiate retail and wholesale prices

3.  **What baseline model do you compare against?**
Linear Regression is use model as the baseline.

4.  **What main hyperparameters did you set or tune?**
For Random Forest I set: n_estimators=100 to create 100 decsion trees to average out the errors, max_depth=10 this limits how complex the rules can get. Limiting  depth is critical to prevent the model from overfitting.

5.  **Which model performed best on the validation of data?**
Random Forest scores the lowest in MAE and scores highest in R2.

# 5. **Evaluation**
"""

metrics_data = {
    'Metric': ['MAE(Mean Absolute Error)', 'MSE(Mean Squared Error)', 'RMSE(Root Mean Squared Error)', 'R2 Score'],
    'Baseline Model': [baseline_mae, baseline_mse, baseline_rmse, baseline_r2],
    'Advance Model' : [rf_mae, rf_mse, rf_rsme, rf_r2]
}

metrics_df = pd.DataFrame(metrics_data)
print(metrics_df.to_string(index=False))

fig, axes = plt.subplots(1,2, figsize=(16,6))

axes[0].scatter(y_test, rf_predictions, alpha=0.3,color='blue')
axes[0].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], '--', lw=2, color='red')
axes[0].set_xlabel('Actual Prices')
axes[0].set_ylabel('Predicted Prices')
axes[0].set_title('Random Forest Regression: Actual vs. Predicted Prices')


residuals = y_test - rf_predictions
sns.histplot(residuals, bins=True, kde=True, ax=axes[1], color='green')
axes[1].axvline(0, color='red', linestyle='dashed')
axes[1].set_xlabel('Residuals Error (Actual Price - Predicted Price)')
axes[1].set_title('Distribution of Model Residuals (Error Spread)')


plt.tight_layout()
st.pyplot(fig)
plt.close(fig)    

"""**1.  What are the main evaluation metrics for each model on the test set?**
The test set metrics for the Linear Regression Baseline are an MAE of 18.46, RMSE of 32.13, and an R2 score of 0.932601. The metrics for the Random Forest Regressor are an MAE of 13.52, RMSE of 22.37, and an R2 score 0.967329.

2.  **How does the best model compare to the baseline model?**
The Random Forest Regressor decisively outperforms the Linear Regression model across all tracking dimensions. It cut the average expected prediction error(MAE) by 4.93 PHP, and slashed the Mean Squared Error(MSE) by more than half(from 1,032.51 to 500.50). This massive drop in MSE shows that the Random Forest is vastly superior at handling severe seasonal price jumps where the linear mode completely fails.

3.  **Are there particular segments where performance is worse?**
Yes. The gap between Random Forest's MAE and RMSE indicates that performance degrades during periods of market volatility. The higher RMSE shows that while the model is highly accurate on average for stable everyday items like grains, it experiences larger absolute errors on high-value, highly volatile segments such as meat or seafood during typhoon seasonsor holiday supply crunches where prices experience sudden, non-linear surges.

4.  **Are prediction errors approximately centered around zero?**
Yes. Given that the Random Forest achieve a high R2 score  of 0.9673 and the residual diagnostic show balanced errors, the predictions are well-centered around zero. The model is statistically unbiased, meaning it does not lean heavily toward systematic overpricing or underpricing. The spread between MAE and RMSE indicates a standard right-tailed distribution where a few underpredictable, extreme agricultural price spikes cause larger errors than normal.

5.  **Does the model meet the business performance goal?**
Yes, it exceeds expecations. For the Bureau of Price Stability, a baseline linear model missing by an average of 18.46 PHP with an RMSE penalty of 32.13 introduces too much risk for government budgeting. By upgrading to the Random Forest Model, the agency reduces its average blind spot to just 13.52 and dramatically lowers its exposure to massive misses(RMSE down to 22.37). Explaining 96.73% of food price variance gives policymakers an incredibly dependable, data-validated early warning system to plan market interventions three months in advance.

# 6.  **Data Visulization**
"""

sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(3,2, figsize=(18,20))
axes = axes.flatten()

df_time = df.groupby('date')['price'].mean().reset_index()
axes[0].plot(df_time['date'], df_time['price'], color='teal', linewidth=1.5)
axes[0].set_title('1. National Average Food Price Over Time', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Year')
axes[0].set_ylabel('Average Price(PHP)')

sns.histplot(df['price'], bins=50, kde=True, ax=axes[1], color='darkorange')
axes[1].axvline(df['price'].mean(), color='red', linestyle='dashed', label=f"Mean: {df['price'].mean():.1f}")
axes[1].axvline(df['price'].median(), color='blue', linestyle='-.', label=f"Median: {df['price'].median(): .1f}")
axes[1].set_title('2. Distribution of Market Prices(Right-Skewed)', fontsize=12, fontweight='bold' )
axes[1].set_xlabel('Price')
axes[1].set_ylabel('Frequency Count')
axes[1].legend()

top_categories = df['category'].value_counts().nlargest(5).index
df_filtered_cat = df[df['category'].isin(top_categories)]
sns.boxplot(data=df_filtered_cat, x='category', y='price', ax=axes[2], palette='Set2', hue='category', legend=False)
axes[2].set_title('3. Price Range Distribution Across Top Food Categories', fontsize=12, fontweight='bold')
axes[2].set_xlabel('Food Category')
axes[2].set_ylabel('Price Range')
axes[2].tick_params(axis='x', rotation=15)

corr_features = ['price', 'month', 'year', 'price_lag_3', 'commodity_encoded']
corr_matrix = df[corr_features].corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5, ax=axes[3])
axes[3].set_title('4. Feature Correlation Matrix', fontsize=12, fontweight='bold')

axes[4].scatter(y_test, rf_predictions, alpha=0.2, color='blue', label='Predicted Prices')
axes[4].plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], '--', lw=2, color='red', label='Perfect Line(y=x)')
axes[4].set_xlabel('Actual Prices')
axes[4].set_ylabel('Predicted Market Price')
axes[4].set_title('5. Advance Model: Predicted vs. Actual Prices', fontsize=12, fontweight='bold')
axes[4].legend()

fig.delaxes(axes[5])
plt.tight_layout()
st.pyplot(fig)
plt.close(fig)

"""1. **What trends or patters do you see in the main metric over time?**
Looking at line plot, there is a clear, long-term upward macroeconomic trajectory inidicating
baseline inflation in the Philippines across the 26 year timeline. Interspersed within this long-term upward trend are sharp, vertical spkes and cyclical fluctuations. These recurring micro-peaks confirm our initial assumption that market food items suffer from seasonal volatilty, likely correlated with yearly monsoon/typhoon disruptions and holiday-driven demand cycles.

2.  **Is the distribution of the target variable symmetric, skewed, or heavy-tailed?**
As shown in Histogram, the distribution of market prices is highly right-skewed. The statistical menas is pulled significantly higher than the median line. The majority of food prodcuts are clustered heavily in the affordable 10 php to 150 php range(everyday staples like grains and vegetables), while a long, sparse heavy-tail stretches out past 400 php to account for luxury or wholesale items like bulk meats and premium seafood.

3.  **Which categories show the highest or lowest values?**
Based on Boxplot, food groups such as Meat, Poultyr, and Fish exhibit much higher median prices, wider overall box stretches, and siginifcantly hihger upper quartiles. Conversely, stape categories like Ceeals and Tubers display tight, compressd box profiles and much lower median values. This confirms that bulk protein presetn a mch higher financial risk and volatility burden to consumers than baseline agricultural grains.

4.  **Which features show teh strongest correlation with the target?**
According to Correlation Matrix Heatmap, the strongest positive correlation with the target price variable belong to price_lag_3. This high coefficient indicates that the market price from three months prior is an exceptional linear baseline and strong mathematical anchor for forecasting future values. Meanwhile, macroeconomic features like year display a moderate positive correlation (capturing gradual inflation), while indivual calander month values show near-zero rely linear correlation, validating why we needed a non-linear model like Random Forest to decipher its cyclical patterns.

5.  **How well do predicted values visually track actual values in the test period?**

As illustrated in Scatter Plot, the predicted values track the actual values with excpetional accuracy, which visually supports our high R2 score of 96.73%. The dense cluster of blue dots tightly hugs the diagonal red Pefect Prediction refernce line. The visual alignment only begins to puff outward slightly at the top end of the chart, showing that the model maintains strong, operational reliability for lower to mid range staple good while experiencing minor variance increases during rare, ultra-high price anomalies.

# 7. **Conclusion & Recommendations**

Business Related Questions:
1.  **How was the average price of Cereals and Tubers vs Meat, Fish and Egg evolved in the Philippines from 2000 to the present?**
Cereals and Tubers remained tightly compressed with a low, highly controlled baseline price. Conversely, Meat, Fish, Eggs experienced massive, steep escalation with wide prce ranges, showing that protein sources have driven the bulk of food budget inflation for Filipino households since 2000.

2.  **Are there spefic period or years that show unusual price spikes compared to the historical average?**
Yes, there are notable anomalies that significantly break the smooth trend line. Including the 2008 Global Food Price Crisis, the 2018 localized rice inlation spke in Philippines, pandemic induced supply chain failures, and seasonal devations corresponding drectly to devastating localized typhoon seasons.

3.  **Which months consistenly show the highest Seasonality index for Meat vs Rice?**
Rice experiences its hghest price pressures during the third quarter (July to September). While, Meat exhibits its highest seasonal index during December.

4.  **Can we build a model that accurately flags a Price Volatility at least 90 days before it occurs?**
By engineering the price_lag_3 feature, the model evaluates market conditions from 90 days prior. THe Random Forest REgressor proved tha an early warning system is hghly achievable, successfully capturing 96.73% of the variance in future food prices. This provides a highly accurate algorithmic window to flag incoming market volatiliy before it hits retail shelves.

5.  **What is the error tolerance for our predictions before they become risky for policy-making?**
For high stakes policy design, baseline model like Linear Regression can lead to potential false price capping and over importation, as its missed by an average of 18.46 with a heavey structural penalty(RMSE = 32.13). However Random Forest model narrowed this risk down with a result of Mean Absolute Error of 13.52 php and an RMSE of 22.37 php.

**Conclusion**

In conclusion, food price volatility in the Philippines is not entirely chaotic; rather, it is highly structured by long-term inflation trends, predictable crop lean seasons, and holiday consumption patterns. While traditional linear forecasting models fail to adpat to severe market disruptions, the advanced Random Forest Regressor captures non-linear economic shocks with an exceptional 96.73% accuracy rate.

**Recommendations**

1.  Use the 3-month forecasting window to plan localized buffer stock releases or adjust import tariff lines before a seasonal peak occrs. For example, when the model predicts a sever lean-season rice spike three months out, import allocatiosn can be finalzed well in advance to ensure shipments arrive precisely when local supply dips.

2.  Use hte pricetype_encoded and commodity_encoded feature weights to deploy targeted transport subsides to logistics providers. by lowering the cost of moving food from farm gates to retail wet markets during predicted high demand months like December for meath, the government can manually ground retail prices close to the models' expected baseline.

3.  To bridge the minor 3.27% variance gap left by historical data, future iterations of the data science pipeline should stream live external features, specifically real-time tropical cyclone paths and global fuel index prices direclty into the model to capture immediate, climate-driven supply shocks.
"""

